export const SETTINGS_PERSONAL_TAB_VALUE = 'personal';
export const SETTINGS_SECURITY_TAB_VALUE = 'security';
export const DEFAULT_SETTINGS_SUBMENU_TAB_VALUE = 0;

export const CHANGE_PASSWORD_MAX_LENGTH = 20;
export const CHANGE_PASSWORD_MIN_LENGTH = 8;

export const M2U_THEME = { TIGER: '21', CITY: '22', ABSTRACT: '23', NATURE: '24' };

export const SETTINGS_PERSONAL_MODULE_TAB_VALUE = { PERSONAL_INFO: 0, THEME: 1, PASSWORD: 0, SECURITY_IMAGE: 1 };
